class SettingsConstants {

  static const String VIEW_PROFILE = "SETTINGS_VIEW_PROFILE";
  static const String PERSONAL_DETAILS = "SETTINGS_PERSONAL_DETAILS";
  static const String EDIT_PROFILE = "SETTINGS_EDIT_PROFILE";
  static const String EDIT_PROFILE_HINT = "SETTINGS_EDIT_PROFILE_HINT";
  static const String PERSONAL_DETAILS_HINT = "SETTINGS_PERSONAL_DETAILS_HINT";
  static const String NOTIFICATIONS = "SETTINGS_NOTIFICATIONS";
  static const String PRIVACY_DEFINITIONS = "SETTINGS_PRIVACY_DEFINITIONS";
  static const String PAYMENTS = "SETTINGS_PAYMENTS";
  static const String CONTACT_US = "SETTINGS_CONTACT_US";
  static const String CONTACT_US_HINT = "SETTINGS_CONTACT_US_HINT";
  static const String HOW_IT_WORKS = "SETTINGS_HOW_IT_WORKS";
  static const String HOW_IT_WORKS_HINT = "SETTINGS_HOW_IT_WORKS_HINT";
  static const String TERMS = "SETTINGS_TERMS";

}