name: professors
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  # icons
  font_awesome_flutter: ^8.5.0
  #Mobx
  mobx: ^0.3.10
  flutter_mobx: ^0.3.4+2
  file_picker: ^1.6.0
  image_picker: ^0.6.5+2
  flutter_rounded_date_picker: 1.0.0
  badges: ^1.1.1
  shared_preferences: 0.5.7

dev_dependencies:
  build_runner: ^1.8.1
  mobx_codegen: ^0.3.10+1

flutter:

  uses-material-design: true

  assets:
    - lang/en.json
    - lang/pt.json
    - assets/icons/payments_icon.png
    - assets/icons/classes_icon.png
    - assets/icons/account_icon.png
    - assets/icons/calendar_icon.png
    - assets/images/loading.gif
    - assets/images/classes_bg.png
    - assets/images/logo_white_circle.png
    - assets/images/onboarding_0.png
    - assets/images/onboarding_1.png
    - assets/images/onboarding_2.png
    - assets/images/onboarding_3.png
    - assets/images/onboarding_4.png

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Light.ttf
    - family: Inter Bold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
    - family: Raleway Bold
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
    - family: Raleway Extra Bold
      fonts:
          - asset: assets/fonts/Raleway-ExtraBold.ttf
    - family: Raleway Light
      fonts:
        - asset: assets/fonts/Raleway-Light.ttf