name: professors
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  # icons
  font_awesome_flutter: ^8.5.0
  #Mobx
  mobx: ^0.3.10
  flutter_mobx: ^0.3.4+2
  file_picker: ^1.6.0
  image_picker: ^0.6.5+2

dev_dependencies:
  build_runner: ^1.8.1
  mobx_codegen: ^0.3.10+1

flutter:

  uses-material-design: true

  assets:
    - lang/en.json
    - lang/pt.json
    - assets/icons/payments_icon.png
    - assets/icons/classes_icon.png
    - assets/icons/account_icon.png
    - assets/icons/calendar_icon.png

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Light.ttf
    - family: Inter Bold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700