class PersonalDetailsConstants {

  String get topHeader => "SETTINGS_PERSONAL_DETAILS_TOP_HEADER";

  String get firstNameLabel => "SETTINGS_PERSONAL_DETAILS_FIRSTNAME_LABEL";
  String get firstNameHint => "SETTINGS_PERSONAL_DETAILS_FIRSTNAME_HINT";
  String get firstNameError => "SETTINGS_PERSONAL_DETAILS_FIRSTNAME_ERROR";

  String get lastNameLabel => "SETTINGS_PERSONAL_DETAILS_LASTNAME_LABEL";
  String get lastNameHint => "SETTINGS_PERSONAL_DETAILS_LASTNAME_HINT";
  String get lastNameError => "SETTINGS_PERSONAL_DETAILS_LASTNAME_ERROR";

  String get genderHint => "SETTINGS_PERSONAL_DETAILS_GENDER_HINT";

  String get emailLabel => "SETTINGS_PERSONAL_DETAILS_EMAIL_LABEL";
  String get emailHint => "SETTINGS_PERSONAL_DETAILS_EMAIL_HINT";
  String get emailError => "SETTINGS_PERSONAL_DETAILS_EMAIL_ERROR";

  String get birthdayHint => "SETTINGS_PERSONAL_DETAILS_BIRTHDAY_HINT";

  String get phoneNumberLabel => "SETTINGS_PERSONAL_DETAILS_PHONE_NUMBER_LABEL";
  String get phoneNumberHint => "SETTINGS_PERSONAL_DETAILS_PHONE_NUMBER_HINT";
  String get phoneNumberError => "SETTINGS_PERSONAL_DETAILS_PHONE_NUMBER_ERROR";

  String get vatLabel => "SETTINGS_PERSONAL_DETAILS_VAT_LABEL";
  String get vatHint => "SETTINGS_PERSONAL_DETAILS_VAT_HINT";
  String get vatError => "SETTINGS_PERSONAL_DETAILS_VAT_ERROR";

  String get nationalityHint => "SETTINGS_PERSONAL_DETAILS_NATIONALITY_HINT";

  String get genderScreenTopHeader => "SETTINGS_PERSONAL_DETAILS_GENDER_SCREEN_TOP_HEADER";
  String get genderScreenSubTitle => "SETTINGS_PERSONAL_DETAILS_GENDER_SCREEN_SUB_TITLE";

}