class PersonalDetailsConstants {

  static const String TOP_HEADER = "SETTINGS_PERSONAL_DETAILS_TOP_HEADER";

  static const String FIRSTNAME_LABEL = "SETTINGS_PERSONAL_DETAILS_FIRSTNAME_LABEL";
  static const String FIRSTNAME_HINT = "SETTINGS_PERSONAL_DETAILS_FIRSTNAME_HINT";
  static const String FIRSTNAME_ERROR = "SETTINGS_PERSONAL_DETAILS_FIRSTNAME_ERROR";

  static const String LASTNAME_LABEL = "SETTINGS_PERSONAL_DETAILS_LASTNAME_LABEL";
  static const String LASTNAME_HINT = "SETTINGS_PERSONAL_DETAILS_LASTNAME_HINT";
  static const String LASTNAME_ERROR = "SETTINGS_PERSONAL_DETAILS_LASTNAME_ERROR";

  static const String GENDER_HINT = "SETTINGS_PERSONAL_DETAILS_GENDER_HINT";

  static const String EMAIL_LABEL = "SETTINGS_PERSONAL_DETAILS_EMAIL_LABEL";
  static const String EMAIL_HINT = "SETTINGS_PERSONAL_DETAILS_EMAIL_HINT";
  static const String EMAIL_ERROR = "SETTINGS_PERSONAL_DETAILS_EMAIL_ERROR";

  static const String BIRTHDAY_HINT = "SETTINGS_PERSONAL_DETAILS_BIRTHDAY_HINT";

  static const String PHONE_NUMBER_LABEL = "SETTINGS_PERSONAL_DETAILS_PHONE_NUMBER_LABEL";
  static const String PHONE_NUMBER_HINT = "SETTINGS_PERSONAL_DETAILS_PHONE_NUMBER_HINT";
  static const String PHONE_NUMBER_ERROR = "SETTINGS_PERSONAL_DETAILS_PHONE_NUMBER_ERROR";

  static const String VAT_LABEL = "SETTINGS_PERSONAL_DETAILS_VAT_LABEL";
  static const String VAT_HINT = "SETTINGS_PERSONAL_DETAILS_VAT_HINT";
  static const String VAT_ERROR = "SETTINGS_PERSONAL_DETAILS_VAT_ERROR";

  static const String NATIONALITY_HINT = "SETTINGS_PERSONAL_DETAILS_NATIONALITY_HINT";

}